# YouTube Transcript Scraper Configuration
# Input Files
YT_CHANNEL_CSV: "yt_channels.csv"
YT_VIDEO_CSV: "yt_videos.csv"
# Output Paths
OUTPUT_YT_VIDEO_CSV: "output_yt_videos.csv"
# Video Filtering Parameters
MIN_LEN_MINS: 0 # Setting to 0 to accept any length videos for testing
MAX_LEN_MINS: 300 # Increased to allow most videos
LANG_INCL_LS: ['en']
FILTER_EXCLUDE_TITLE: ['going deeper', 'sunday school']
DATE_START: "" # Format: YYYY-MM-DD
DATE_END: "" # Format: YYYY-MM-DD
# Method Order - try methods in this order
# Options: 'api', 'yt-dlp', 'audio'
METHOD_ORDER_LS: ['audio'] # ['api', 'yt-dlp', 'audio']
# Speech-to-Text Processing
PROCESS_SST_AUDIO: true # If true, convert downloaded audio to transcripts
# Rate Limiting and Anti-Blocking
MIN_WAIT_TIME: 0.5 # Minimum wait time in seconds
# Channel Processing Limits
MAX_PAGES_PER_CHANNEL: 5 # Maximum number of result pages to process per channel
MAX_VIDEOS_PER_CHANNEL: 10 # Maximum number of videos to process per channel
# Logging Configuration
LOGGING_LEVEL: "INFO" # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL

# Audio Download Settings
AUDIO_QUALITY: "64"  # MP3 quality in kbps (lower = smaller files)
USE_GPU_ACCELERATION: true  # Use GPU acceleration for audio processing
MAX_AUDIO_LENGTH_MINS: 30  # Maximum length in minutes for audio files
SPLIT_LONG_AUDIO: true  # Whether to split long audio files into chunks
AUDIO_CHUNK_MINS: 10  # Size of each chunk in minutes if splitting

# Optional: Configure Whisper model size
# Options: tiny, base, small, medium, large
WHISPER_MODEL_SIZE: "base"  # Smaller models are faster but less accurate